### ISSUE TITLE
Responsive design à faire sur la page Fabrication

### ISSUE THREAD

**Issue by ThomasFlandin** [ThomasFlandin/ProjetWeb-Chocolatier#12]

**Comment by Ale-ksi** [comment]
Je pense avoir terminé.
Dans le doute je te laisse vérifier et fermer le problème.

**Comment by ThomasFlandin** [comment]
Quelques petites rectifications (ajout scrollbar si besoin + ajout évènement ontouch pour les mobiles (car les hovers ne fonctionnent pas).
