### ISSUE TITLE
Séparer fond de la forme formation.html

### ISSUE THREAD

**Issue by ThomasFlandin** [ThomasFlandin/ProjetWeb-Chocolatier#13]
Enlever les <code>&lt;br /&gt;</code> et faire les espaces en css avec des margins et paddings.

**Comment by Ale-ksi** [comment]
Suppression des <br> et ajout de CSS pour conserver la forme.

**Comment by Ale-ksi** [comment]
Suppression des balises br  et ajout de CSS pour conserver la forme.

Voir commit: c32e275
