### ISSUE TITLE
L'image SVG n'attends pas le scroll pour s'afficher.

### ISSUE THREAD

**Issue by Ale-ksi** [ThomasFlandin/ProjetWeb-Chocolatier#24]
Il faut rajouter du JS ou le modifier pour que les partie de l'image s'affichent en fonction de la hauteur du scroll.
(On peut aussi faire apparaître les div texte de la même manière)

**Comment by ThomasFlandin** [comment]
Trop long à faire pour l'image svg.

Mais ScroolReveal a rajouter sur les div > p.

**Comment by ThomasFlandin** [comment]
Pas urgent, problèmes #26 puis #25 à régler en priorité.

**Comment by ThomasFlandin** [comment]
Pas le temps
